### ISSUE TITLE
llvm error / core dump on Arch Linux

### ISSUE THREAD

**Issue by flechtwerkflechtwerk** [grame-cncm/faustlive#45]
I haven't used FaustLive in a week or so, but suddenly it crashes at start with the following error:
```
fAudioArchitecture number of items = 1
AudioCreator::indexChanged 0
FaustLive: /usr/include/llvm/IR/Instructions.h:959: static llvm::GetElementPtrInst* llvm::GetElementPtrInst::Create(llvm::Type*, llvm::Value*, llvm::ArrayRef<llvm::Value*>, const llvm::Twine&, llvm::Instruction*): Assertion `PointeeType && "Must specify element type"' failed.
[1]    10884 abort (core dumped)  FaustLive
```

I'm not sure what changed at my system that could have led to this error. I'm running Arch Linux with Realtime kernel, the latest Faust package (I tried replacing it with the git version from AUR which didn't change anything) and with JACK running.

The same error/crash happens to the Mephisto.lv2 plugin, by the way. (It immediatly crashed Reaper or Ardour when trying to load it.) It also used to run before. Compiling Faust to Supercollider still works flawlessly though.

**Comment by sletz** [comment]
Which  version of faust are you using ?I guess you are compiling libfaust with LLVM 13?

**Comment by flechtwerkflechtwerk** [comment]
I have Faust 2.37.3. LLVM 13 is installed on my system -- so I guess it is used for compilation? Or do I have to specify that somewhere?

**Comment by sletz** [comment]
This was fixed in Faust 2.38.1, see https://github.com/grame-cncm/faust/commit/85e9746684462b1334d6c77997bad872b8774497.
You'll have to use Git master-dev, or go back to LLVM 12.

**Comment by flechtwerkflechtwerk** [comment]
Downgrading to LLVM 12 didn't solve the problem, but I'll wait until Faust 2.38.1 reaches the Arch repositories then. (I'll close the issue after having it tried again then.) Thanks for the quick reply!

**Comment by sletz** [comment]
LLVM 12 not solving? That is really strange !

**Comment by flechtwerkflechtwerk** [comment]
My mistake - I didn't. I now recompiled Faust to 2.38.4 (with LLVM 13) and everything works fine again. Thanks a lot for the help!
